create table ck_zxzs1019.chat_history on cluster ch_cluster_all
(
	id UUID,
	base_id Nullable(String),
	primary_uuid String,
	sub_uuid String,
	seat_dialog_content Nullable(String),
	customer_dialog_content Nullable(String),
	connect_time DateTime,
	hangup_time Nullable(DateTime),
	call_time UInt32,
	workorder_type Nullable(String),
	call_reason Nullable(String),
	work_order_element Nullable(String),
	knowledge_recomment_num Nullable(UInt32),
	template_violation_num Nullable(UInt32),
	flow_violation_num Nullable(UInt32),
	hit_template_id String default '-2',
	hit_flow_id String default '-2',
	quality_score Nullable(Float64),
	check_score Nullable(Float64),
	template_avg_score Nullable(Float64),
	flow_avg_score Nullable(Float64),
	appeal_count Nullable(UInt32),
	appeal_time Nullable(DateTime),
	appeal_status Nullable(String),
	appeal_handler Nullable(String),
	appeal_id Nullable(String),
	gmt_create DateTime,
	gmt_modify Nullable(DateTime),
	total_donus Nullable(UInt32),
	total_deduction Nullable(UInt32),
	hit_template Nullable(String),
	hit_flow Nullable(String),
	hit_rule_id String default '-2',
	hit_rule Nullable(String),
	fatal_error Nullable(UInt32),
	hit_work_template Nullable(String),
	mute_time Nullable(String),
	seat_sentences_num Nullable(UInt32),
	seat_total_speed Nullable(UInt32),
	seat_avg_speed Nullable(UInt32),
	seat_total_volume Nullable(UInt32),
	seat_avg_volume Nullable(UInt32),
	flow_pop_screen_count Nullable(UInt32),
	template_pop_screen_count Nullable(UInt32),
	risk_pop_screen_count Nullable(UInt32),
	grab_words_count Nullable(UInt32),
	call_violation_template Nullable(String),
	call_violation_flow Nullable(String),
	call_violation_flow_node Nullable(String),
	call_violation_rule Nullable(String),
	mute_count Nullable(UInt32),
	template_quality_msg Nullable(String),
	template_bonus_num Nullable(UInt32),
	hit_script_map_id Nullable(String),
	hit_script_map_info Nullable(String),
	hit_script_map_prompt Nullable(String),
	hit_script_map_node Nullable(String),
	acquisition_method Nullable(UInt32),
	acquisition_method_id Nullable(String),
	tenant_id Nullable(String),
	department_id Nullable(String),
	department_tree Nullable(String),
	channel_type Nullable(String),
	call_type Nullable(String),
	online_type Nullable(String),
	seat_name Nullable(String),
	seat_group Nullable(String),
	seat_group_path Nullable(String),
	skill_group_id Nullable(UInt32),
	skill_group_name Nullable(String),
	customer_num Nullable(String),
	customer_identification_type Nullable(String),
	customer_identification Nullable(String),
	statistical_flag Nullable(String),
	warn_pop_screen_count Nullable(UInt32),
	seat_id Nullable(String),
	seat_group_id Nullable(UInt64),
	script_map_broadcast Nullable(String),
	script_map_score Nullable(Float64),
	script_map_pop_screen_count Nullable(UInt32),
	violation_script_map Nullable(String),
	violation_script_map_node Nullable(String),
	violation_script_map_num Nullable(UInt32)
)
engine = Distributed('ch_cluster_all', 'ck_zxzs1019', 'chat_history_local', rand());

create table ck_zxzs1019.chat_history_base on cluster ch_cluster_all
(
	id UUID,
	channel_type Nullable(String),
	call_type Nullable(String),
	online_type Nullable(String),
	primary_uuid String,
	sub_uuid String,
	seat_id String,
	seat_name Nullable(String),
	seat_group Nullable(String),
	seat_group_id Nullable(UInt64),
	seat_group_path Nullable(String),
	skill_group_name Nullable(String),
	skill_group_id Nullable(UInt32),
	customer_num Nullable(String),
	customer_identification_type Nullable(String),
	customer_identification Nullable(String),
	statistical_flag Nullable(String),
	gmt_create DateTime,
	gmt_modify Nullable(DateTime),
	connect_time DateTime,
	hangup_time Nullable(DateTime),
	tenant_id Nullable(String),
	department_id Nullable(String),
	department_tree Nullable(String)
)
engine = Distributed('ch_cluster_all', 'ck_zxzs1019', 'chat_history_base_local', rand());

create table ck_zxzs1019.chat_history_base_local on cluster ch_cluster_all
(
	id UUID,
	channel_type Nullable(String),
	call_type Nullable(String),
	online_type Nullable(String),
	primary_uuid String,
	sub_uuid String,
	seat_id String,
	seat_name Nullable(String),
	seat_group Nullable(String),
	seat_group_id Nullable(UInt64),
	seat_group_path Nullable(String),
	skill_group_name Nullable(String),
	skill_group_id Nullable(UInt32),
	customer_num Nullable(String),
	customer_identification_type Nullable(String),
	customer_identification Nullable(String),
	statistical_flag Nullable(String),
	gmt_create DateTime,
	gmt_modify Nullable(DateTime),
	connect_time DateTime,
	hangup_time Nullable(DateTime),
	tenant_id Nullable(String),
	department_id Nullable(String),
	department_tree Nullable(String)
)
engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/chat_history_base_local_1019', '{replica}')
PARTITION BY toYYYYMM(gmt_create)
PRIMARY KEY (gmt_create, primary_uuid, sub_uuid, seat_id, connect_time)
ORDER BY (gmt_create, primary_uuid, sub_uuid, seat_id, connect_time)
SETTINGS index_granularity = 8192;

create table ck_zxzs1019.chat_history_detail on cluster ch_cluster_all
(
	id UUID,
	base_id Nullable(String),
	primary_uuid String,
	sub_uuid String,
	talker_type Nullable(String),
	talk_time Nullable(DateTime),
	content Nullable(String),
	content_order Nullable(UInt32),
	recmatch_degree Nullable(String),
	recommend_speech Nullable(String),
	recommend_text Nullable(String),
	seat_evaluation String default '0',
	workorder_type Nullable(String),
	workorder_element Nullable(String),
	call_reason Nullable(String),
	hit_template Nullable(String),
	hit_template_id String default '-2',
	hit_flow Nullable(String),
	hit_flow_id String default '-2',
	hit_flow_node Nullable(String),
	hit_flow_node_id Nullable(String),
	hit_pop_screen Nullable(String),
	hit_pop_screen_id Nullable(String),
	hit_rule Nullable(String),
	hit_rule_id String default '-2',
	emotion Nullable(UInt32),
	other_info Nullable(String),
	gmt_create DateTime,
	gmt_modify Nullable(DateTime),
	extension Nullable(String),
	recommend_title Nullable(String),
	recommend_knowledge Nullable(String),
	porit_tag Nullable(String),
	tenant_id Nullable(String),
	department_id Nullable(String),
	department_tree Nullable(String),
	channel_type Nullable(String),
	call_type Nullable(String),
	online_type Nullable(String),
	seat_id Nullable(String),
	seat_name Nullable(String),
	seat_group Nullable(String),
	seat_group_id Nullable(UInt64),
	seat_group_path Nullable(String),
	skill_group_id Nullable(UInt32),
	skill_group_name Nullable(String),
	customer_num Nullable(String),
	customer_identification_type Nullable(String),
	customer_identification Nullable(String),
	statistical_flag Nullable(String),
	connect_time Nullable(DateTime),
	hangup_time Nullable(DateTime),
	hit_script_map_id Nullable(String),
	hit_script_map_node_id Nullable(String),
	hit_script_map_rule_id Nullable(String)
)
engine = Distributed('ch_cluster_all', 'ck_zxzs1019', 'chat_history_detail_local', rand());

create table ck_zxzs1019.chat_history_detail_local on cluster ch_cluster_all
(
	id UUID,
	base_id Nullable(String),
	primary_uuid String,
	sub_uuid String,
	talker_type Nullable(String),
	talk_time Nullable(DateTime),
	content Nullable(String),
	content_order Nullable(UInt32),
	recmatch_degree Nullable(String),
	recommend_speech Nullable(String),
	recommend_text Nullable(String),
	seat_evaluation String default '0',
	workorder_type Nullable(String),
	workorder_element Nullable(String),
	call_reason Nullable(String),
	hit_template Nullable(String),
	hit_template_id String default '-2',
	hit_flow Nullable(String),
	hit_flow_id String default '-2',
	hit_flow_node Nullable(String),
	hit_flow_node_id Nullable(String),
	hit_pop_screen Nullable(String),
	hit_pop_screen_id Nullable(String),
	hit_rule Nullable(String),
	hit_rule_id String default '-2',
	emotion Nullable(UInt32),
	other_info Nullable(String),
	gmt_create DateTime,
	gmt_modify Nullable(DateTime),
	extension Nullable(String),
	recommend_title Nullable(String),
	recommend_knowledge Nullable(String),
	porit_tag Nullable(String),
	tenant_id Nullable(String),
	department_id Nullable(String),
	department_tree Nullable(String),
	channel_type Nullable(String),
	call_type Nullable(String),
	online_type Nullable(String),
	seat_id Nullable(String),
	seat_name Nullable(String),
	seat_group Nullable(String),
	seat_group_id Nullable(UInt64),
	seat_group_path Nullable(String),
	skill_group_id Nullable(UInt32),
	skill_group_name Nullable(String),
	customer_num Nullable(String),
	customer_identification_type Nullable(String),
	customer_identification Nullable(String),
	statistical_flag Nullable(String),
	connect_time Nullable(DateTime),
	hangup_time Nullable(DateTime),
	hit_script_map_id Nullable(String),
	hit_script_map_node_id Nullable(String),
	hit_script_map_rule_id Nullable(String)
)
engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/chat_history_detail_local_1019', '{replica}')
PARTITION BY toYYYYMM(gmt_create)
PRIMARY KEY (gmt_create, primary_uuid, sub_uuid)
ORDER BY (gmt_create, primary_uuid, sub_uuid)
SETTINGS index_granularity = 8192;

create table ck_zxzs1019.chat_history_local on cluster ch_cluster_all
(
	id UUID,
	base_id Nullable(String),
	primary_uuid String,
	sub_uuid String,
	seat_dialog_content Nullable(String),
	customer_dialog_content Nullable(String),
	connect_time DateTime,
	hangup_time Nullable(DateTime),
	call_time UInt32,
	workorder_type Nullable(String),
	call_reason Nullable(String),
	work_order_element Nullable(String),
	knowledge_recomment_num Nullable(UInt32),
	template_violation_num Nullable(UInt32),
	flow_violation_num Nullable(UInt32),
	hit_template_id String default '-2',
	hit_flow_id String default '-2',
	quality_score Nullable(Float64),
	check_score Nullable(Float64),
	template_avg_score Nullable(Float64),
	flow_avg_score Nullable(Float64),
	appeal_count Nullable(UInt32),
	appeal_time Nullable(DateTime),
	appeal_status Nullable(String),
	appeal_handler Nullable(String),
	appeal_id Nullable(String),
	gmt_create DateTime,
	gmt_modify Nullable(DateTime),
	total_donus Nullable(UInt32),
	total_deduction Nullable(UInt32),
	hit_template Nullable(String),
	hit_flow Nullable(String),
	hit_rule_id String default '-2',
	hit_rule Nullable(String),
	fatal_error Nullable(UInt32),
	hit_work_template Nullable(String),
	mute_time Nullable(String),
	seat_sentences_num Nullable(UInt32),
	seat_total_speed Nullable(UInt32),
	seat_avg_speed Nullable(UInt32),
	seat_total_volume Nullable(UInt32),
	seat_avg_volume Nullable(UInt32),
	flow_pop_screen_count Nullable(UInt32),
	template_pop_screen_count Nullable(UInt32),
	risk_pop_screen_count Nullable(UInt32),
	grab_words_count Nullable(UInt32),
	call_violation_template Nullable(String),
	call_violation_flow Nullable(String),
	call_violation_flow_node Nullable(String),
	call_violation_rule Nullable(String),
	mute_count Nullable(UInt32),
	template_quality_msg Nullable(String),
	template_bonus_num Nullable(UInt32),
	hit_script_map_id Nullable(String),
	hit_script_map_info Nullable(String),
	hit_script_map_prompt Nullable(String),
	hit_script_map_node Nullable(String),
	acquisition_method Nullable(UInt32),
	acquisition_method_id Nullable(String),
	tenant_id Nullable(String),
	department_id Nullable(String),
	department_tree Nullable(String),
	channel_type Nullable(String),
	call_type Nullable(String),
	online_type Nullable(String),
	seat_name Nullable(String),
	seat_group Nullable(String),
	seat_group_path Nullable(String),
	skill_group_id Nullable(UInt32),
	skill_group_name Nullable(String),
	customer_num Nullable(String),
	customer_identification_type Nullable(String),
	customer_identification Nullable(String),
	statistical_flag Nullable(String),
	warn_pop_screen_count Nullable(UInt32),
	seat_id Nullable(String),
	seat_group_id Nullable(UInt64),
	script_map_broadcast Nullable(String),
	script_map_score Nullable(Float64),
	script_map_pop_screen_count Nullable(UInt32),
	violation_script_map Nullable(String),
	violation_script_map_node Nullable(String),
	violation_script_map_num Nullable(UInt32)
)
engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/chat_history_local_1019', '{replica}')
PARTITION BY toYYYYMM(gmt_create)
PRIMARY KEY (gmt_create, primary_uuid, sub_uuid, connect_time)
ORDER BY (gmt_create, primary_uuid, sub_uuid, connect_time)
SETTINGS index_granularity = 8192;

create table ck_zxzs1019.chat_history_route on cluster ch_cluster_all
(
	id UUID,
	call_type Nullable(String),
	primary_uuid String,
	sub_uuid String,
	interactives Nullable(String),
	gmt_create DateTime,
	tenant_id Nullable(String),
	department_id Nullable(String),
	department_tree Nullable(String)
)
engine = Distributed('ch_cluster_all', 'ck_zxzs1019', 'chat_history_route_local', rand());

create table ck_zxzs1019.chat_history_route_local on cluster ch_cluster_all
(
	id UUID,
	call_type Nullable(String),
	primary_uuid String,
	sub_uuid String,
	interactives Nullable(String),
	gmt_create DateTime,
	tenant_id Nullable(String),
	department_id Nullable(String),
	department_tree Nullable(String)
)
engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/chat_history_route_local_1019', '{replica}')
PARTITION BY toYYYYMM(gmt_create)
PRIMARY KEY (gmt_create, primary_uuid, sub_uuid)
ORDER BY (gmt_create, primary_uuid, sub_uuid)
SETTINGS index_granularity = 8192;

create table ck_zxzs1019.da_call_word_rel on cluster ch_cluster_all
(
	id UInt64,
	tenant_id UInt64,
	word String,
	call_year UInt16,
	call_day UInt16,
	call_hour UInt16,
	uid String,
	sub_uid String,
	gmt_create DateTime,
	gmt_modify DateTime
)
engine = MergeTree ORDER BY id
SETTINGS index_granularity = 8192;

create table ck_zxzs1019.da_stat_uid on cluster ch_cluster_all
(
	stat_id UInt64,
	uid_col String
)
engine = MergeTree ORDER BY stat_id
SETTINGS index_granularity = 8192;

create table ck_zxzs1019.knowledge_recommend_mysql on cluster ch_cluster_all
(
	ID Nullable(String),
	SEAT_ID Nullable(String),
	PRIMARY_UUID Nullable(String),
	SUB_UUID Nullable(String),
	OPERATOR_TYPE Nullable(UInt32),
	DIALOG_ORDER Nullable(UInt32),
	KNOWLEDGE_ID Nullable(String),
	ANSWER_ID Nullable(String),
	CONTENT Nullable(String),
	QUESTION_STD Nullable(String),
	SCORE Nullable(String),
	TITLE Nullable(String),
	SUBJECT Nullable(String),
	KNOWLEDGE_TYPE Nullable(UInt32),
	TRADITIONAL_KNOWLEDGE_URL Nullable(String),
	CREATE_TIME Nullable(String),
	EVALUATE_CONTENT Nullable(String),
	EVALUATE_STATE Nullable(String),
	INACCURATE_TYPE Nullable(String),
	EVALUATE_TIME Nullable(String),
	TENANT_ID Nullable(String),
	DEPARTMENT_ID Nullable(String),
	DEPARTMENT_TREE Nullable(String),
	ANSWER_CREAT_TIME Nullable(String),
	DATE_PLACEHOLDER Nullable(DateTime)
)
engine = JDBC('mysql-dev-1019', '', 'knowledge_recommend');

create table ck_zxzs1019.quality_review_mysql on cluster ch_cluster_all
(
	ID Nullable(String),
	PRIMARY_UUID Nullable(String),
	SUB_UUID Nullable(String),
	SEAT_ID Nullable(String),
	SEAT_NAME Nullable(String),
	SEAT_GROUP_ID Nullable(String),
	SEAT_GROUP Nullable(String),
	QUALITY_SCORE Nullable(Decimal(8,2)),
	MACHINE_SCORE Nullable(Decimal(8,2)),
	MANUAL_SCORE Nullable(Decimal(10,2)),
	TEMPLATE_VIOLATION_NUM Nullable(UInt32),
	TEMPLATE_NAME Nullable(String),
	CONNECT_TIME Nullable(DateTime),
	HANGUP_TIME Nullable(DateTime),
	CALL_TIME Nullable(UInt32),
	APPEAL_COUNT Nullable(UInt32),
	LAST_APPEAL_TIME Nullable(DateTime),
	APPEAL_STATUS Nullable(UInt32),
	CHECK_STATUS Nullable(UInt32),
	CHECKER Nullable(String),
	CHECKER_NAME Nullable(String),
	CHECKER_ROLE Nullable(UInt32),
	OPINION Nullable(String),
	CHECK_TIME Nullable(DateTime),
	UPDATE_TIME Nullable(DateTime),
	TENANT_ID Nullable(String),
	DEPARTMENT_ID Nullable(String),
	DEPARTMENT_TREE Nullable(String)
)
engine = JDBC('mysql-dev-1019', '', 'quality_review');

